name: flutter_camera
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  camera_web: ^0.3.3 # Add the latest version of camera_web
  camera: ^0.11.0+1
  flutter_riverpod: ^3.0.0-dev.3
  riverpod_annotation: ^3.0.0-dev.3
  google_generative_ai: ^0.4.3
  flutter_dotenv: ^5.1.0
  image: ^3.0.1

dev_dependencies:
  build_runner:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  riverpod_generator: ^3.0.0-dev.11
  riverpod_lint: ^3.0.0-dev.4

flutter:
  uses-material-design: true

  assets:
  - .env
